language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: dSOeBG3omA0O7EflA3wuBFU89qdUupSXjVmCDzqhVYCG4wc1Z0Q/T7bC0nHDBdTOuq/3yL/y7X1D/QM38wpbRuUMAPgXM1hYNWIYErTJf4agZNzg+nvm4KPP0aUjN4qitouGn2tIFdot3DQq1N7boZIVhuovaPoQ1OYFCbiRhIgoj6rp2Hcj7cxd2uVfdW0wgPjelXM/f1mLgNsBIU7AXnv6ypU4Zg9L9KAPTrzVyJ6ObbFahoA4x4qxv2dHNp7k1JPYsNs3XNKvckerP39z+TUgbz+uHiowKllad5QOggk4YV3pW9+f2wmg2yodlmPd+c6zSRU83V8vztO8G9p0YPzjF3moaLvQK1hMJOFG9JgZ/ErZkYFXj8/K9Kc+vLLvsGj5/xHTS0gMNQEd/uhvYeboK5/EyujXkKuwVL1oc5nD8iodioOC/EoPRqjV0OVYignP4IsUj4r5RfOiklFjCEfyQL4jGfNDIrgqwt5aCimbYLbHnlP0tJgs7t0HpUXjmf2QZRNPhpxnIgENdnobvGkVL7yJ6JDwLc/S1q79527pjD7xyVuRA1qmyjcpbla2ofDP9StSaUszloPMKYdUZjgHZjwHLgPOHQy4JgcnaGIeMuKc2mbhGHT1Gnp5zAio5QyapwS6G2rOiTjFpiGTWgkOIYW2uULp7A6EK9H7BMc=
  app: band-mom
  on:
    repo: HypeUFO/band-mom
